# Generated by Django 5.2.4 on 2025-11-16 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterQualityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(help_text='Date and time of the record')),
                ('temperature', models.FloatField(help_text='Water temperature in °C')),
                ('tds', models.FloatField(help_text='Total Dissolved Solids in ppm')),
                ('turbidity', models.FloatField(help_text='Turbidity in NTU')),
                ('source', models.CharField(choices=[('Blynk', 'Blynk Sensor'), ('Manual', 'Manual Entry')], default='Blynk', help_text='Source of the data', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Optional notes or remarks', null=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
